# Generated by Django 4.1.5 on 2023-02-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
