# Generated by Django 4.1.5 on 2023-02-02 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_remove_response_survey_surveyresponse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='choice',
        ),
        migrations.AddField(
            model_name='response',
            name='answer',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
