# Generated by Django 4.1.5 on 2023-02-02 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0008_remove_response_choice_response_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('number', 'Number'), ('date', 'Date'), ('radio', 'Radio'), ('checkbox', 'Checkbox'), ('select', 'Select')], max_length=8),
        ),
    ]
