# Generated by Django 4.1.5 on 2023-02-02 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0009_alter_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='survey_response',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='surveys.surveyresponse'),
        ),
    ]
