# Generated by Django 4.1.5 on 2023-02-02 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0010_alter_response_survey_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='survey_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.surveyresponse'),
        ),
    ]
